        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">Dashboard</a>
                    <div class="nav-collapse collapse">
                        <p class="navbar-text pull-right">
                            Logged in as
                            <a href="<?php echo $this->userProfileUrl($this->currentUser); ?>" class="navbar-link">
                                <?php echo $this->escape($this->currentUser->username); ?>
                            </a> |
                            <a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout'), null, true); ?>">Logout</a>
                        </p>
                        <ul class="nav">
                            <li class="<?php echo ($this->currentNav === 'home') ? 'active' : '' ?>"><a href="/">Home</a></li>
                            <li class="<?php echo ($this->currentNav === 'points') ? 'active' : '' ?>"><a href="/points">All Points</a></li>
                            <li class="<?php echo ($this->currentNav === 'newpoint') ? 'active' : '' ?>"><a href="/points/new">Award Point</a></li>
                            <li class="<?php echo ($this->currentNav === 'about') ? 'active' : '' ?>"><a href="/about">About</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>