<div class="game-overview well span6 offset4">

    <h3>Game Overview</h3>

    <p>
        The premise of this game is to better track all of the Badass/Dumbass
        things the we say on a daily basis. This is done through positive &
        negative points. With every event there is a recipient & a witness, one
        of which, will enter the event into the system for the other party to
        approve. This is done using the honor system so please man up. If you say
        something dumb it's best to just own that shit like a boss.
    </p>

    <hr>

    <p>
        After a point has been entered into the system other users can comment
        on it. There is also a like/dislike system to track comment popularity.
    </p>

    <hr>

    <p>
        Notifications will be sent out (via e-mail) to any party related to a
        point or point comments so you can keep up with current entries into the
        system.
    </p>

    <hr>

    <p>
        We have been unofficially playing this game for a little over a year
        between each other and keeping score became impossible very quickly, but
        we found that trying to catch the other person saying something straight
        up foolish was a fun challenge.
    </p>

    <hr>

    <p>
        Ergo this game was created. It still doesn't even have a name so some help
        with that would not be turned away.
    </p>

</div>